apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 2 #number of replicas you want to run in pod
  selector:
    matchLabels:
      tier: frontend
      env: dev
  template:     #OK, so now that we know we want 2 replicas, we need to answer the question: “Replicas of what?”  They’re defined by templates:
    metadata:
      labels:
        env: dev
        tier: frontend
    spec:
      containers:
      - name: dpods
        image: arun161087/docker-http-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"