apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  labels:
    env: dev
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
        env: dev
    spec:
      containers:
      - name: pods
        image: arun161087/docker-http-server